//! Autogenerated weights for pallet_tipping
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-12-31, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// target/release/myriad
// benchmark
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet=pallet-tipping
// --extrinsic=*
// --steps=20
// --repeat=10
// --heap-pages=4096
// --template=./.maintain/pallet-weight-template.hbs
// --output=./pallets/tipping/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_tipping.
pub trait WeightInfo {
	fn pay_content() -> Weight;
	fn withdraw_fee() -> Weight;
	fn withdraw_reward() -> Weight;
	fn send_tip() -> Weight;
	fn claim_reference() -> Weight;
	fn claim_tip() -> Weight;
}

/// Weights for pallet_tipping using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: System Account (r:2 w:2)
	// Storage: Tipping WithdrawalBalance (r:1 w:1)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: Tipping ReceiptIds (r:1 w:1)
	// Storage: Tipping Receipts (r:0 w:1)
	fn pay_content() -> Weight {
		Weight::from_ref_time(165_900_000_u64)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	// Storage: Tipping WithdrawalBalance (r:1 w:1)
	// Storage: System Account (r:2 w:2)
	fn withdraw_fee() -> Weight {
		Weight::from_ref_time(165_800_000_u64)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	// Storage: Tipping RewardBalance (r:2 w:1)
	// Storage: System Account (r:2 w:2)
	fn withdraw_reward() -> Weight {
		Weight::from_ref_time(85_800_000_u64)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	// Storage: System Account (r:1 w:1)
	// Storage: Tipping TipsBalanceByReference (r:1 w:1)
	fn send_tip() -> Weight {
		Weight::from_ref_time(122_100_000_u64)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: Tipping TipsBalanceByReference (r:2 w:2)
	// Storage: System Account (r:1 w:1)
	fn claim_reference() -> Weight {
		Weight::from_ref_time(165_100_000_u64)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	// Storage: Tipping TipsBalanceByReference (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	fn claim_tip() -> Weight {
		Weight::from_ref_time(107_400_000_u64)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: System Account (r:2 w:2)
	// Storage: Tipping WithdrawalBalance (r:1 w:1)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: Tipping ReceiptIds (r:1 w:1)
	// Storage: Tipping Receipts (r:0 w:1)
	fn pay_content() -> Weight {
		Weight::from_ref_time(165_900_000_u64)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	// Storage: Tipping WithdrawalBalance (r:1 w:1)
	// Storage: System Account (r:2 w:2)
	fn withdraw_fee() -> Weight {
		Weight::from_ref_time(165_800_000_u64)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	// Storage: Tipping RewardBalance (r:2 w:1)
	// Storage: System Account (r:2 w:2)
	fn withdraw_reward() -> Weight {
		Weight::from_ref_time(85_800_000_u64)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	// Storage: System Account (r:1 w:1)
	// Storage: Tipping TipsBalanceByReference (r:1 w:1)
	fn send_tip() -> Weight {
		Weight::from_ref_time(122_100_000_u64)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	// Storage: Tipping TipsBalanceByReference (r:2 w:2)
	// Storage: System Account (r:1 w:1)
	fn claim_reference() -> Weight {
		Weight::from_ref_time(165_100_000_u64)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	// Storage: Tipping TipsBalanceByReference (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	fn claim_tip() -> Weight {
		Weight::from_ref_time(107_400_000_u64)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
