//! Autogenerated weights for pallet_tipping
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-04-01, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// target/release/myriad
// benchmark
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet=pallet_tipping
// --extrinsic=*
// --steps=20
// --repeat=10
// --heap-pages=4096
// --raw
// --template=./.maintain/pallet-weight-template.hbs
// --output=./pallets/tipping/src/weights.rs


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_tipping.
pub trait WeightInfo {
	fn send_tip(s: u32, ) -> Weight;
	fn claim_reference() -> Weight;
	fn claim_tip() -> Weight;
}

/// Weights for pallet_tipping using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: Server ServerById (r:1 w:0)
	// Storage: Tipping TipsBalanceByReference (r:1 w:1)
	// Storage: System Account (r:1 w:0)
	fn send_tip(_s: u32, ) -> Weight {
		91_220_000_u64
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: Server ServerById (r:1 w:0)
	// Storage: Tipping TipsBalanceByReference (r:2 w:2)
	fn claim_reference() -> Weight {
		77_444_000_u64
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	// Storage: Tipping TipsBalanceByReference (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	fn claim_tip() -> Weight {
		93_113_000_u64
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: Server ServerById (r:1 w:0)
	// Storage: Tipping TipsBalanceByReference (r:1 w:1)
	// Storage: System Account (r:1 w:0)
	fn send_tip(_s: u32, ) -> Weight {
		91_220_000_u64
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	// Storage: Server ServerById (r:1 w:0)
	// Storage: Tipping TipsBalanceByReference (r:2 w:2)
	fn claim_reference() -> Weight {
		77_444_000_u64
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	// Storage: Tipping TipsBalanceByReference (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	fn claim_tip() -> Weight {
		93_113_000_u64
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
