[profile.release]
panic = 'unwind'

[workspace]
members = [
	'nodes/appchain',
	'nodes/parachain',
	'nodes/standalone',
	'pallets/*',
	'runtimes/appchain',
	'runtimes/parachain',
	'runtimes/standalone',
]
