version: '3'

services:
  node:
    image: myriadsocial/myriad-node:1.0.0
    volumes:
      - data:/data
    command: >
      myriad
      --base-path /data
      --dev
    ports:
      - 30333:30333
      - 9933:9933
      - 9944:9944
    networks:
      myriad:
        ipv4_address: 172.27.1.1
        aliases:
          - node

volumes:
  data:

networks:
  myriad:
    external: true
