
//! Autogenerated weights for pallet_currency
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2021-10-12, STEPS: `[20, ]`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/myriad
// benchmark
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet=pallet_currency
// --extrinsic=*
// --steps=20
// --repeat=10
// --heap-pages=4096
// --raw
// --output=./pallets/currency/src/weight.rs

#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_currency.
pub trait WeightInfo {
	fn add_currency() -> Weight;
	fn update_balance(s: u32, ) -> Weight;
	fn transfer(s: u32, ) -> Weight;
}

/// Weights for pallet_currency using the Myriad node and recommended hardware.
pub struct MyriadWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for MyriadWeight<T> {
	fn add_currency() -> Weight {
		(76_000_000_u64)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	fn update_balance(s: u32, ) -> Weight {
		(84_469_000_u64)
			// Standard Error: 88_000
			.saturating_add((138_000_u64).saturating_mul(s as Weight))
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	fn transfer(_s: u32, ) -> Weight {
		(135_925_000_u64)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn add_currency() -> Weight {
		(76_000_000_u64)
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	fn update_balance(s: u32, ) -> Weight {
		(84_469_000_u64)
			// Standard Error: 88_000
			.saturating_add((138_000_u64).saturating_mul(s as Weight))
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	fn transfer(_s: u32, ) -> Weight {
		(135_925_000_u64)
			.saturating_add(RocksDbWeight::get().reads(3 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
}
