apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myriad-node.sessionInjectionJobName" . }}
  labels:
data:
  inject_session_keys.sh: |-
    #!/bin/bash

    set -euo pipefail
    set -x

    RPC_ENDPOINT=${1}
    STATEFULSET_NAME=${2}

    for key in /keys/*; do
        [ -e "$key" ] || continue
        PUBLIC_KEY=$(cat "$key")


        case "$key" in
            /keys/grandpa)
                KEY_TYPE=gran
                ;;
            /keys/babe)
                KEY_TYPE=babe
                ;;
            /keys/imonline)
                KEY_TYPE=imon
                ;;
            /keys/beefy)
                KEY_TYPE=befy
                ;;
            *)
                KEY_TYPE=
                ;;
        esac

        if [ ! -z "${KEY_TYPE}" ]; then
            KEY_SEED=$(cat /key-seed/key-seed)

            curl -H "Content-Type: application/json" \
                --data '{ "jsonrpc":"2.0", "method":"author_insertKey", "params":["'"${KEY_TYPE}"'", "'"${KEY_SEED}"'", "'"${PUBLIC_KEY}"'"],"id":1 }' \
                "${RPC_ENDPOINT}"

        fi
    done

    # restart pod to start using the grandpa key
    CURRENT_DIR=$(dirname "$0")

    /scripts/restart_pods.sh "${STATEFULSET_NAME}"

  restart_pods.sh: |-
    #!/bin/bash
    STATEFULSET_NAME=${1}

    kubectl scale statefulset ${STATEFULSET_NAME} --replicas=0
    kubectl scale statefulset ${STATEFULSET_NAME} --replicas=1
