{{- if .Values.ingress.httpRPC.enabled -}}
{{- $ingressHttpRPCName := include "myriad-node.ingressHttpRPCName" . -}}
{{- $serviceHttpRPCName := include "myriad-node.serviceHttpRPCName" . -}}
{{- $serviceHttpRPCPort := .Values.services.httpRPC.port -}}
{{- if and .Values.ingress.httpRPC.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.httpRPC.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.httpRPC.annotations "kubernetes.io/ingress.class" .Values.ingress.httpRPC.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $ingressHttpRPCName }}
  labels:
    {{- include "myriad-node.labels" . | nindent 4 }}
  {{- with .Values.ingress.httpRPC.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.httpRPC.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.httpRPC.className }}
  {{- end }}
  {{- if .Values.ingress.httpRPC.tls }}
  tls:
    {{- range .Values.ingress.httpRPC.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.httpRPC.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $serviceHttpRPCName }}
                port:
                  number: {{ $serviceHttpRPCPort }}
              {{- else }}
              serviceName: {{ $serviceHttpRPCName }}
              servicePort: {{ $serviceHttpRPCPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}

{{- if and .Values.ingress.httpRPC.enabled .Values.ingress.websocketRPC.enabled }}
---

{{- end }}
{{- if .Values.ingress.websocketRPC.enabled }}
{{- $ingressWebsocketRPCName := include "myriad-node.ingressWebsocketRPCName" . -}}
{{- $serviceWebsocketRPCName := include "myriad-node.serviceWebsocketRPCName" . -}}
{{- $serviceWebsocketRPCPort := .Values.services.websocketRPC.port -}}
{{- if and .Values.ingress.websocketRPC.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.websocketRPC.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.websocketRPC.annotations "kubernetes.io/ingress.class" .Values.ingress.websocketRPC.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $ingressWebsocketRPCName }}
  labels:
    {{- include "myriad-node.labels" . | nindent 4 }}
  {{- with .Values.ingress.websocketRPC.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.websocketRPC.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.websocketRPC.className }}
  {{- end }}
  {{- if .Values.ingress.websocketRPC.tls }}
  tls:
    {{- range .Values.ingress.websocketRPC.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.websocketRPC.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $serviceWebsocketRPCName }}
                port:
                  number: {{ $serviceWebsocketRPCPort }}
              {{- else }}
              serviceName: {{ $serviceWebsocketRPCName }}
              servicePort: {{ $serviceWebsocketRPCPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end -}}
