{{- if .Values.serviceAccount.create -}}
{{- range .Values.config.nodes }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "myriad-node.serviceAccountName" $ }}-{{ .name }}
  labels:
    {{- include "myriad-node.labels" $ | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: [ {{ include "myriad-node.nodeKeySecretName" $ }}-{{ .name }} ]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    verbs: ["get"]
    resources: ["statefulsets"]
  - apiGroups: ["apps"]
    verbs: ["get", "patch"]
    resources: ["statefulsets/scale"]

---

{{- end }}
{{- end }}
