{{- if .Values.serviceAccount.create -}}
{{- if and .Values.serviceAccount.name (ne .Values.serviceAccount.name "default") }}
{{- range .Values.nodes }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "myriad-node.serviceAccountName" $ }}-{{ .name }}
  labels:
    {{- include "myriad-node.labels" $ | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: [ {{ include "myriad-node.nodeKeySecretName" $ }}-{{ .name }} ]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]

---

{{- end }}
{{- end }}
{{- end }}
