{{- if .Values.secrets.nodeKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-node.nodeKeySecret" . }}
type: Opaque
data:
  nodeKey: {{ .Values.secrets.nodeKey | b64enc }}
{{- end }}
{{- if .Values.secrets.sessionKeys }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-node.sessionKeySecret" . }}
type: Opaque
data:
  granSessionKey: {{ .Values.secrets.sessionKeys.gran | b64enc }}
  babeSessionKey: {{ .Values.secrets.sessionKeys.babe | b64enc }}
  imonSessionKey: {{ .Values.secrets.sessionKeys.imon | b64enc }}
  beefSessionKey: {{ .Values.secrets.sessionKeys.beef | b64enc }}
{{- end }}
