{{ if .Values.config.nodeKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-node.nodeKeySecretName" . }}
type: Opaque
data:
  node-key: {{ .Values.config.nodeKey | b64enc }}
{{ end }}
