{{- range .Values.nodes }}
{{- if and .keys.private .keys.public }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-node.nodeKeySecretName" $ }}-{{ .name }}
type: Opaque
data:
  private: {{ .keys.private | b64enc }}
  public: {{ .keys.public | b64enc }}

---

{{- end }}
{{- end }}
