{{- range .Values.config.nodes }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "myriad-node.fullname" $ }}-{{ .name }}
  labels:
    {{- include "myriad-node.labels" $ | nindent 4 }}
    component: {{ .name }}
    {{- if .validator }}
    part-of: validator
    {{- else }}
    part-of: full-node
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: p2p
      port: 30333
      protocol: TCP
      targetPort: p2p
    - name: http-rpc
      port: 9933
      protocol: TCP
      targetPort: http-rpc
    - name: websocket-rpc
      port: 9944
      protocol: TCP
      targetPort: websocket-rpc
    - name: metrics
      port: 9615
      protocol: TCP
      targetPort: metrics
  clusterIP: None
  selector:
    {{- include "myriad-node.selectorLabels" $ | nindent 4 }}
    component: {{ .name }}
    {{- if .validator }}
    part-of: validator
    {{- else }}
    part-of: full-node
    {{- end }}

---

{{- end }}
{{- if .Values.services.httpRPC.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "myriad-node.serviceHttpRPCName" . }}
  labels:
    {{- include "myriad-node.labels" . | nindent 4 }}
    part-of: full-node
spec:
  type: ClusterIP
  ports:
    - name: http-rpc
      port: 9933
      protocol: TCP
      targetPort: http-rpc
  selector:
    {{- include "myriad-node.selectorLabels" . | nindent 4 }}
    part-of: full-node

{{- end }}
{{- if and .Values.services.httpRPC.enabled .Values.services.websocketRPC.enabled }}
---

{{- end }}
{{- if .Values.services.websocketRPC.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "myriad-node.serviceWebsocketRPCName" . }}
  labels:
    {{- include "myriad-node.labels" . | nindent 4 }}
    part-of: full-node
spec:
  type: ClusterIP
  ports:
    - name: websocket-rpc
      port: 9944
      protocol: TCP
      targetPort: websocket-rpc
  selector:
    {{- include "myriad-node.selectorLabels" . | nindent 4 }}
    part-of: full-node

{{- end }}
