apiVersion: v1
kind: Service
metadata:
  name: {{ include "myriad-node.fullname" . }}-headless
  labels:
    {{- include "myriad-node.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 30333
      targetPort: p2p
      protocol: TCP
      name: p2p
    - port: 9933
      targetPort: http-rpc
      protocol: TCP
      name: http-rpc
    - port: 9944
      targetPort: websocket-rpc
      protocol: TCP
      name: websocket-rpc
    - port: 9615
      targetPort: prometheus
      protocol: TCP
      name: prometheus
  clusterIP: None
  selector:
    {{- include "myriad-node.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "myriad-node.fullname" . }}-p2p
  labels:
    {{- include "myriad-node.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 30333
      targetPort: p2p
      protocol: TCP
      name: p2p
  externalTrafficPolicy: Local
  selector:
    {{- include "myriad-node.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "myriad-node.fullname" . }}-http-rpc
  labels:
    {{- include "myriad-node.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9933
      targetPort: http-rpc
      protocol: TCP
      name: http-rpc
  selector:
    {{- include "myriad-node.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "myriad-node.fullname" . }}-websocket-rpc
  labels:
    {{- include "myriad-node.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9944
      targetPort: websocket-rpc
      protocol: TCP
      name: websocket-rpc
  selector:
    {{- include "myriad-node.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "myriad-node.fullname" . }}-prometheus
  labels:
    {{- include "myriad-node.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9615
      targetPort: prometheus
      protocol: TCP
      name: prometheus
  selector:
    {{- include "myriad-node.selectorLabels" . | nindent 4 }}
