{{- range .Values.nodes }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "myriad-node.fullname" $ }}-{{ .name }}
  labels:
    {{- include "myriad-node.labels" $ | nindent 4 }}
    component: {{ .name }}
    {{- if .validator }}
    part-of: validator
    {{- else }}
    part-of: full-node
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 30333
      targetPort: p2p
      protocol: TCP
      name: p2p
    - port: 9933
      targetPort: http-rpc
      protocol: TCP
      name: http-rpc
    - port: 9944
      targetPort: websocket-rpc
      protocol: TCP
      name: websocket-rpc
    - port: 9615
      targetPort: prometheus
      protocol: TCP
      name: prometheus
  clusterIP: None
  selector:
    {{- include "myriad-node.selectorLabels" $ | nindent 4 }}
    component: {{ .name }}
    {{- if .validator }}
    part-of: validator
    {{- else }}
    part-of: full-node
    {{- end }}

---

{{- end }}
