{{- range .Values.nodes }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "myriad-node.fullname" $ }}-{{ .name }}
  labels:
    {{- include "myriad-node.labels" $ | nindent 4 }}
    component: {{ .name }}
    {{- if .validator }}
    part-of: validator
    {{- else }}
    part-of: full-node
    {{- end }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "myriad-node.selectorLabels" $ | nindent 6 }}
      component: {{ .name }}
      {{- if .validator }}
      part-of: validator
      {{- else }}
      part-of: full-node
      {{- end }}
  serviceName: {{ include "myriad-node.fullname" $ }}-{{ .name }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: {{ $.Values.volume.storageClassName }}
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ $.Values.volume.dataSize }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      labels:
        {{- include "myriad-node.selectorLabels" $ | nindent 8 }}
        component: {{ .name }}
        {{- if .validator }}
        part-of: validator
        {{- else }}
        part-of: full-node
        {{- end }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- if $.Values.serviceAccount.create }}
      serviceAccountName: {{ include "myriad-node.serviceAccountName" $ }}-{{ .name }}
      {{- else }}
      serviceAccountName: {{ include "myriad-node.serviceAccountName" $ }}
      {{- end }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command: [ "sh" ]
          args:
            - -c
            - exec /usr/local/bin/myriad
              --base-path /data
              {{- if $.Values.config.chain }}
              --chain {{ $.Values.config.chain }}
              {{- end }}
              {{- if .keys.private }}
              --node-key $(cat /etc/secrets/node-key/KEY)
              {{- end }}
              {{- if .name }}
              --name {{ .name }}
              {{- end }}
              {{- if .validator }}
              --validator
              {{- end }}
              --port 30333
              --rpc-cors all
              --rpc-methods unsafe
              --rpc-port 9933
              --ws-port 9944
              --unsafe-rpc-external
              --unsafe-ws-external
              --prometheus-port 9615
              --prometheus-external
              --no-telemetry
              --enable-offchain-indexing true
              {{- $name := .name }}
              {{- range $value := $.Values.nodes }}
              {{- if and $value.bootnode (ne $value.name $name ) }}
              --bootnodes=/dns/{{ include "myriad-node.name" $ }}-{{ $value.name }}-0.{{ include "myriad-node.name" $ }}-{{ $value.name }}.{{ $.Release.Namespace }}.svc.cluster.local/tcp/30333/p2p/{{ $value.keys.public }}
              {{- end }}
              {{- end }}
              {{- range $value := $.Values.config.bootnodes }}
              --bootnodes={{ $value }}
              {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
            {{- if .keys.private }}
            - name: node-key
              mountPath: /etc/secrets/node-key
            {{- end }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          ports:
            - name: p2p
              containerPort: 30333
              protocol: TCP
            - name: http-rpc
              containerPort: 9933
              protocol: TCP
            - name: websocket-rpc
              containerPort: 9944
              protocol: TCP
            - name: prometheus
              containerPort: 9615
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http-rpc
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /health
              port: http-rpc
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          startupProbe:
            httpGet:
              path: /health
              port: http-rpc
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
            successThreshold: 1
      {{- if .keys.private }}
      volumes:
        - name: node-key
          secret:
            secretName: {{ include "myriad-node.nodeKeySecretName" $ }}-{{ .name }}
            items:
              - key: private
                path: KEY
              - key: public
                path: KEY_PUB
      {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml $ | nindent 8 }}
      {{- end }}

---

{{- end }}
