//! Autogenerated weights for pallet_escrow
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2021-11-18, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/myriad
// benchmark
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet=pallet_escrow
// --extrinsic=*
// --steps=20
// --repeat=10
// --heap-pages=4096
// --raw
// --output=./pallets/escrow/src/weights.rs
// --template=./.maintain/pallet-weight-template.hbs


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_escrow.
pub trait WeightInfo {
	fn send_tip(s: u32, ) -> Weight;
}

/// Weights for pallet_escrow using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: Platform Platforms (r:1 w:0)
	// Storage: Currency Currency (r:1 w:0)
	// Storage: Escrow PeopleBalance (r:1 w:1)
	// Storage: Escrow PostBalance (r:1 w:1)
	// Storage: Currency Accounts (r:1 w:1)
	fn send_tip(_s: u32, ) -> Weight {
		369_718_000_u64
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: Platform Platforms (r:1 w:0)
	// Storage: Currency Currency (r:1 w:0)
	// Storage: Escrow PeopleBalance (r:1 w:1)
	// Storage: Escrow PostBalance (r:1 w:1)
	// Storage: Currency Accounts (r:1 w:1)
	fn send_tip(_s: u32, ) -> Weight {
		369_718_000_u64
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
}
