name: Check Links

on:
  pull_request:
    branches:
      - main

concurrency:
  group: check-link-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check-link-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check Link Markdown
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          config-file: ".github/workflows/mlc_config.json"
