name: Main automation

on:
  push:
    branches:
      - main

concurrency:
  group: main-automation

jobs:
  compute-build-info:
    runs-on: ubuntu-latest

    outputs:
      sha_short: ${{ steps.build-info.outputs.sha_short }}
      date: ${{ steps.build-info.outputs.date }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compute build info
        id: build-info
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=date::$(date +'%Y%m%d')"

  build-and-publish-docker-image:
    runs-on: ubuntu-latest

    needs: compute-build-info

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: .maintain/docker/Dockerfile
          tags: |
            ${{ github.repository }}:${{ needs.compute-build-info.outputs.sha_short }}-${{ needs.compute-build-info.outputs.date }}
            ${{ github.repository }}:latest-alpha
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    runs-on: ubuntu-latest

    needs: [compute-build-info, build-and-publish-docker-image]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.DEV_GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.DEV_GCP_SA_KEY }}
          export_default_credentials: true

      - name: Get the GKE credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: myriad
          location: asia-southeast2-a

      - name: Get secrets
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            bootnode1PublicKey:${{ secrets.DEV_GCP_PROJECT_ID }}/bootnode1PublicKey
            bootnode1PrivateKey:${{ secrets.DEV_GCP_PROJECT_ID }}/bootnode1PrivateKey
            node1PublicKey:${{ secrets.DEV_GCP_PROJECT_ID }}/node1PublicKey
            node1PrivateKey:${{ secrets.DEV_GCP_PROJECT_ID }}/node1PrivateKey
            node2PublicKey:${{ secrets.DEV_GCP_PROJECT_ID }}/node2PublicKey
            node2PrivateKey:${{ secrets.DEV_GCP_PROJECT_ID }}/node2PrivateKey

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Deploy bootnode 1
        run: |
          helm upgrade myriad-node-boot-1 .maintain/kubernetes \
            --install \
            --set-string image.tag=${{ needs.compute-build-info.outputs.sha_short }}-${{ needs.compute-build-info.outputs.date }} \
            --set-string config.chain=development \
            --set-string config.nodeKey=${{ steps.secrets.outputs.bootnode1PrivateKey }} \
            --set-string config.name=myriad-node-boot-1 \
            --set-string volume.storageClassName=premium-rwo \
            --set-string volume.dataSize=50Gi \
          kubectl rollout status deployment/myriad-node-boot-1

      - name: Deploy validator node 1
        run: |
          helm upgrade myriad-node-validator-1 .maintain/kubernetes \
            --install \
            --set-string image.tag=${{ needs.compute-build-info.outputs.sha_short }}-${{ needs.compute-build-info.outputs.date }} \
            --set-string config.chain=development \
            --set-string config.nodeKey=${{ steps.secrets.outputs.bootnode1PrivateKey }} \
            --set-string config.name=myriad-node-validator-1 \
            --set config.validator=true \
            --set-string config.bootnodes[0]=/dns4/myriad-node-boot-1.default.svc.cluster.local/tcp/30333/p2p/${{ steps.secrets.outputs.bootnode1PublicKey }} \
            --set-string volume.storageClassName=premium-rwo \
            --set-string volume.dataSize=50Gi \
          kubectl rollout status deployment/myriad-node-validator-1

      - name: Deploy validator node 2
        run: |
          helm upgrade myriad-node-validator-2 .maintain/kubernetes \
            --install \
            --set-string image.tag=${{ needs.compute-build-info.outputs.sha_short }}-${{ needs.compute-build-info.outputs.date }} \
            --set-string config.chain=development \
            --set-string config.nodeKey=${{ steps.secrets.outputs.bootnode2PrivateKey }} \
            --set-string config.name=myriad-node-validator-2 \
            --set config.validator=true \
            --set-string config.bootnodes[0]=/dns4/myriad-node-boot-1.default.svc.cluster.local/tcp/30333/p2p/${{ steps.secrets.outputs.bootnode1PublicKey }} \
            --set-string volume.storageClassName=premium-rwo \
            --set-string volume.dataSize=50Gi \
          kubectl rollout status deployment/myriad-node-validator-2

  jira:
    runs-on: ubuntu-latest

    needs: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Find issue in commit messages
        uses: atlassian/gajira-find-issue-key@master
        id: find-issue
        with:
          from: commits

      - name: Transition issue
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.find-issue.outputs.issue }}
          transition: 'READY TO TEST'
