name: Main automation

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.*'

concurrency:
  group: main-automation

jobs:
  compute-build-info:
    runs-on: ubuntu-20.04
    outputs:
      sha_short: ${{ steps.build-info.outputs.sha_short }}
      date: ${{ steps.build-info.outputs.date }}
      latest_tag: ${{ steps.build-info.outputs.latest_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Compute build info
        id: build-info
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=date::$(date +'%Y%m%d')"

          version=${GITHUB_REF#refs/*/}
          echo $version
          echo "::set-output name=latest_tag::$version"

  build:
    runs-on: ubuntu-20.04
    needs: compute-build-info
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: clippy, rustfmt
          target: wasm32-unknown-unknown
          override: true
          default: true
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0
      - name: Cargo build
        run: cargo build --release
      # build-and-publish-docker-image
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Copy binnary file
        run: cp target/release/myriad .
      - name: Build and push
        if: ${{ github.event.ref_type == 'branch' }} && ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: .maintain/docker/injected-binnary.Dockerfile
          tags: |
            ${{ github.repository }}:${{ needs.compute-build-info.outputs.sha_short }}-${{ needs.compute-build-info.outputs.date }}
            ${{ github.repository }}:latest-pre-alpha
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: Build and push alpha
        if: "contains(needs.compute-build-info.outputs.latest_tag, 'alpha')"
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: .maintain/docker/injected-binnary.Dockerfile
          tags: |
            ${{ github.repository }}:${{ needs.compute-build-info.outputs.latest_tag }}
            ${{ github.repository }}:latest-alpha
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: Build and push beta
        if: "contains(needs.compute-build-info.outputs.latest_tag, 'beta')"
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: .maintain/docker/injected-binnary.Dockerfile
          tags: |
            ${{ github.repository }}:${{ needs.compute-build-info.outputs.latest_tag }}
            ${{ github.repository }}:latest-beta
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: Build and push pre-release
        if: "contains(needs.compute-build-info.outputs.latest_tag, 'rc')"
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: .maintain/docker/injected-binnary.Dockerfile
          tags: |
            ${{ github.repository }}:${{ needs.compute-build-info.outputs.latest_tag }}
            ${{ github.repository }}:latest-rc
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: Build and push release
        if: "startsWith(github.ref, 'refs/tags/') && !contains(needs.compute-build-info.outputs.latest_tag, 'alpha') && !contains(needs.compute-build-info.outputs.latest_tag, 'beta') && !contains(needs.compute-build-info.outputs.latest_tag, 'rc')"
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: .maintain/docker/injected-binnary.Dockerfile
          tags: |
            ${{ github.repository }}:${{ needs.compute-build-info.outputs.latest_tag }}
            ${{ github.repository }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      # publish-draft-release
      - name: Build changelog
        if: "startsWith(github.ref, 'refs/tags/')"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration: '.github/workflows/rcb_config.json'
      - name: Create draft pre-release
        if: "contains(needs.compute-build-info.outputs.latest_tag, 'alpha') || contains(needs.compute-build-info.outputs.latest_tag, 'beta') || contains(needs.compute-build-info.outputs.latest_tag, 'rc')"
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.build_changelog.outputs.changelog }}
          draft: true
          prerelease: true
          files: |
            ./target/release/wbuild/myriad-runtime/myriad_runtime.compact.compressed.wasm
            ./target/release/myriad
      - name: Create draft release
        if: "startsWith(github.ref, 'refs/tags/') && !contains(needs.compute-build-info.outputs.latest_tag, 'alpha') && !contains(needs.compute-build-info.outputs.latest_tag, 'beta') && !contains(needs.compute-build-info.outputs.latest_tag, 'rc')"
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.build_changelog.outputs.changelog }}
          draft: true
          files: |
            ./target/release/wbuild/myriad-runtime/myriad_runtime.compact.compressed.wasm
            ./target/release/myriad
