name: Publish docker image for new releases

on:
  release:
    types:
      - published

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/release/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: .maintain/docker/Dockerfile
          tags: |
            myriadsocial/myriad-node:latest
            myriadsocial/myriad-node:${{ github.event.release.tag_name }}
          build-args: |
            VCS_REF=${{ github.ref }}
            BUILD_DATE=${{ github.event.release.published_at }}
          cache-from: type=local,src=/tmp/release/.buildx-cache
          cache-to: type=local,dest=/tmp/release/.buildx-cache-new

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/release/.buildx-cache
          mv /tmp/release/.buildx-cache-new /tmp/release/.buildx-cache

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
