name: Publish draft release candidate

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-rc*'

concurrency:
  group: publish-draft-release-candidate

jobs:
  publish-draft-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration: '.github/workflows/rcb_config.json'
      - name: Re-use cache rust or cargo project
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/
            target/
            resource/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.build_changelog.outputs.changelog }}
          draft: true
          prerelease: true
          files: |
            ./target/release/wbuild/myriad-runtime/myriad_runtime.compact.compressed.wasm
            ./target/release/myriad
            ./resource/chain-spec.json
            ./resource/SHA256SUMS
