name: Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'RELEASE'
        required: true 
        type: string

concurrency:
  group: release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: cardinalby/git-get-release-action@v1
        id: get_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseName: ${{ inputs.release }}
      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.get_release.outputs.id }}
