name: Tester

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - ".maintain/**"
      - ".dockerignore"
      - "LICENSE"

concurrency:
  group: tester-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      test: ${{ steps.filter.outputs.test }}
      markdown: ${{ steps.filter.outputs.markdown }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            test:
              - 'node/**'
              - 'pallets/**'
              - 'runtime/**'
              - '.**'
              - '**.toml'
              - '**.lock'
            markdown:
              - 'docs/**'
              - '**.md'

  test-code:
    needs: changes
    if: ${{ needs.changes.outputs.test == 'true' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install protobuf-compiler
        run: sudo apt install -y protobuf-compiler
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-07-24
          components: clippy, rustfmt
          target: wasm32-unknown-unknown
          override: true
          default: true
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0
      - name: Change nightly version
        run: sed -i 's/+nightly/+nightly-2022-07-24/g' .maintain/test.sh
      - name: Test code
        run: ./.maintain/test.sh

  check-link-markdown:
    needs: changes
    if: ${{ needs.changes.outputs.markdown == 'true' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check link markdown
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          config-file: ".github/workflows/mlc_config.json"
