name: Test Code

on:
  pull_request:
    branches:
      - main
      - development # TODO : remove this, if we use one branch

jobs:
  test-code:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2021-07-17
          components: clippy, rustfmt
          target: wasm32-unknown-unknown
          override: true
          default: true

      - name: Test Code
        run: ./.maintain/test.sh
